apiVersion: v1
kind: Service
metadata:
  name: stripe-payment-api
  labels:
    app: stripe-payment-api
spec:
  type: ClusterIP
  selector:
    app: stripe-payment-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
